### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jaca1119** [jaca1119/OpenWeatherTask#2]
- [x]  Get data from api in thread
- [x] Schedule api call in fixed rate
- [x] Allow user to pick locations
- [x] Show better output
